### ISSUE TITLE
Errors with the Jbrowse config setup script on WSL

### ISSUE THREAD

**Issue by That-Thing** [soybase/jekyll-soybase#5] opened 2023-06-06 15:57 UTC
When running _scripts/jbrowse-tracks.sh on WSL, several genomes and annotations cause errors. This issue is specific to WSL; The script runs fine on native Linux. 

All of the genomes that cause errors have a source URL ending in either `.fa.gz` or `.fsa_nt.gz`

Genomes:
```
Identifier: Hefeng25_IGA1002.gnm1.L69T
   ›   .genome_main.fna.gzrgument:
   ›   See more help with --help
Identifier: Lee.gnm2.K7BV
   ›   .genome_main.fna.gzrgument:
   ›   See more help with --help
Identifier: Wenfeng7_IGA1001.gnm1.L0QH
   ›   .genome_main.fna.gzrgument:
   ›   See more help with --help
Identifier: Wm82_IGA1008.gnm1.5CQQ
   ›   .genome_main.fna.gzrgument:
   ›   See more help with --help
```
Annotations:
```
Identifier: Huaxia3_IGA1007.gnm1.ann1.LKC7
   ›   .gene_models_main.gff3.gzt:
   ›   See more help with --help
Identifier: Lee.gnm2.ann1.1FNT
   ›   .gene_models_main.gff3.gzt:
   ›   See more help with --help
Identifier: Zh13.gnm2.ann1.FJ3G
   ›   .gene_models_main.gff3.gzt:
   ›   See more help with --help
```

This issue occurs on both Ubuntu 20.04 (WSL version 1) and 22.04 (WSL version 2)

**Comment by StevenCannon-USDA** [comment] 2024-01-05 20:29
I assume that we have a sufficient workaround, and the issue is > 6 months old. I'll close it. Reopen if necessary.

**Closed as completed by StevenCannon-USDA** 2024-01-05 20:29 UTC
